#http://localhost:9090/swagger-ui.html
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/rentACar
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      show-sql: 'true'
      ddl-auto: update
server:
  port: 9090